# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Based"
license = "MIT"
licenselink = "https://github.com/JasonTurley/hugo-based/LICENSE"
description = "A Hugo theme based on Based Cooking"
homepage = "https://github.com/JasonTurley/hugo-based/"
tags = ["minimal"]
features = []
min_version = "0.41.0"

[author]
  	name = "Jason Turley"
  	homepage = "https://jasonturley.xyz"

[original]
	name = "Based Cooking"
	homepage = "https://based.cooking"
	repo = "https://github.com/lukesmithxyz/based.cooking"
