baseURL = "https://example.com"

# The name of the theme to use
theme = "hugo-based"

# Basic metadata for the website
title = "What to Code"
author = "Jason Turley"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[permalinks]
	projects = "/:slug/"
	tags 	 = "/projects/:slug"

